import { precacheAndRoute } from 'workbox-precaching';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly, NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// BACKGROUND SYNC FOR OFFLINE PROGRESS
const bgSyncPlugin = new BackgroundSyncPlugin('progress-sync-queue', {
  maxRetentionTime: 24 * 60 // Retry for max of 24 Hours (specified in minutes)
});

// Intercept POST requests to progress endpoints and use BackgroundSync
registerRoute(
  /\/api\/learning\/.*\/complete/,
  new NetworkOnly({
    plugins: [bgSyncPlugin]
  }),
  'POST'
);

registerRoute(
  /\/api\/learning\/progress\/skill/,
  new NetworkOnly({
    plugins: [bgSyncPlugin]
  }),
  'POST'
);

// OTHER CACHING STRATEGIES (Carried over from our previous config)
registerRoute(
  /\/api\/(profile|dashboard|leaderboard|learning\/progress|learning\/(\d+|practice))/i,
  new NetworkFirst({
    cacheName: 'dynamic-user-data',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 // 1 day
      })
    ]
  }),
  'GET'
);

registerRoute(
  /\/api\/learning\/.*Bank/i,
  new CacheFirst({
    cacheName: 'static-data-banks',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30 // 30 days
      })
    ]
  }),
  'GET'
);

// PUSH NOTIFICATIONS
self.addEventListener('push', (event) => {
  if (event.data) {
    const data = event.data.json();
    const options = {
      body: data.body,
      icon: data.icon || '/pwa-192x192.png',
      badge: '/favicon.svg',
      vibrate: [100, 50, 100],
      data: data.data || { url: '/' }
    };

    event.waitUntil(
      self.registration.showNotification(data.title, options)
    );
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const urlToOpen = event.notification.data.url;
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        let client = windowClients[i];
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, open a new window/tab
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
