// TraceMaster Data — Alphabets and Vocabulary for all 8 supported languages
// Languages: en, hi, ur, ta, te, bn, mr, mwr

// ============================================================
// TRACE LETTERS — Full alphabets per language
// ============================================================
export const TRACE_LETTERS = {
  hi: [
    // Vowels (स्वर)
    { letter: 'अ', name: 'A', instructions: 'Draw the vertical line, add the curved stroke on top, then the headline (Shirorekha).' },
    { letter: 'आ', name: 'Aa', instructions: 'Start like अ, then add a vertical line on the right with a small curve.' },
    { letter: 'इ', name: 'I', instructions: 'Draw two small curves and a vertical line with the headline on top.' },
    { letter: 'ई', name: 'Ee', instructions: 'Draw the vertical line with a longer curve extending below the headline.' },
    { letter: 'उ', name: 'U', instructions: 'Draw the curved hook shape below the headline.' },
    { letter: 'ऊ', name: 'Oo', instructions: 'Draw a deeper curved hook extending further below.' },
    { letter: 'ए', name: 'E', instructions: 'Draw the left triangle shape, then the vertical line and headline.' },
    { letter: 'ऐ', name: 'Ai', instructions: 'Like ए but with an extra caret mark above the headline.' },
    { letter: 'ओ', name: 'O', instructions: 'Draw अ first, then add the ा matra and the ो hook on top.' },
    { letter: 'औ', name: 'Au', instructions: 'Like ओ but with an extra caret mark above.' },
    { letter: 'अं', name: 'Am', instructions: 'Draw अ and place a dot (bindu) above the headline.' },
    { letter: 'अः', name: 'Aha', instructions: 'Draw अ and place two dots (visarga) to the right.' },
    // Consonants (व्यंजन)
    { letter: 'क', name: 'Ka', instructions: 'Draw the center loop curving right, then the top headline.' },
    { letter: 'ख', name: 'Kha', instructions: 'Draw the vertical line, a right-side loop, and the headline.' },
    { letter: 'ग', name: 'Ga', instructions: 'Draw a curved vertical stroke hooking left at the bottom, then headline.' },
    { letter: 'घ', name: 'Gha', instructions: 'Draw the top loop, the vertical body, a small bottom hook, then headline.' },
    { letter: 'ङ', name: 'Nga', instructions: 'Draw the two-loop figure resembling a numeral, then headline.' },
    { letter: 'च', name: 'Cha', instructions: 'Draw the curved top, vertical stroke, and headline.' },
    { letter: 'छ', name: 'Chha', instructions: 'Draw the distinctive double-loop body, then headline.' },
    { letter: 'ज', name: 'Ja', instructions: 'Draw the vertical line with a left-curving hook at top, then headline.' },
    { letter: 'झ', name: 'Jha', instructions: 'Draw the central cross strokes with curved tails, then headline.' },
    { letter: 'ञ', name: 'Nya', instructions: 'Draw the two connected loops side-by-side, then headline.' },
    { letter: 'ट', name: 'Ta (hard)', instructions: 'Draw the curved cap and the downward stroke, then headline.' },
    { letter: 'ठ', name: 'Tha (hard)', instructions: 'Draw the circular loop body and vertical tail, then headline.' },
    { letter: 'ड', name: 'Da (hard)', instructions: 'Draw the top curve and the descending stroke, then headline.' },
    { letter: 'ढ', name: 'Dha (hard)', instructions: 'Draw the round loop with the descending tail, then headline.' },
    { letter: 'ण', name: 'Na (hard)', instructions: 'Draw the complex body with loops and tail, then headline.' },
    { letter: 'त', name: 'Ta', instructions: 'Draw horizontal line curling downward, then the headline.' },
    { letter: 'थ', name: 'Tha', instructions: 'Draw the circular loop and vertical stroke, then headline.' },
    { letter: 'द', name: 'Da', instructions: 'Draw the rounded body opening to the left, then headline.' },
    { letter: 'ध', name: 'Dha', instructions: 'Draw the curved body with the right-side vertical, then headline.' },
    { letter: 'न', name: 'Na', instructions: 'Draw the left vertical, bottom curve, right vertical, then headline.' },
    { letter: 'प', name: 'Pa', instructions: 'Draw the vertical line and the right-curving loop, then headline.' },
    { letter: 'फ', name: 'Pha', instructions: 'Draw the central loop and side strokes, then headline.' },
    { letter: 'ब', name: 'Ba', instructions: 'Draw the vertical line with a left-side loop, then headline.' },
    { letter: 'भ', name: 'Bha', instructions: 'Draw the rounded body with the central stroke, then headline.' },
    { letter: 'म', name: 'Ma', instructions: 'Draw vertical line, bottom loop, horizontal bar, then headline.' },
    { letter: 'य', name: 'Ya', instructions: 'Draw the two-loop figure flowing right, then headline.' },
    { letter: 'र', name: 'Ra', instructions: 'Draw the small left-curving stroke below the headline.' },
    { letter: 'ल', name: 'La', instructions: 'Draw the vertical line with the bottom-left curve, then headline.' },
    { letter: 'व', name: 'Va', instructions: 'Draw the open loop curving right, then headline.' },
    { letter: 'श', name: 'Sha', instructions: 'Draw three vertical strokes connected at top by the headline.' },
    { letter: 'ष', name: 'Sha (hard)', instructions: 'Draw the complex loop body under the headline.' },
    { letter: 'स', name: 'Sa', instructions: 'Draw the flowing S-like curve, then headline.' },
    { letter: 'ह', name: 'Ha', instructions: 'Draw the vertical line with the distinctive right-side loops, then headline.' },
    { letter: 'क्ष', name: 'Ksha', instructions: 'Draw the combined conjunct form of क and ष, then headline.' },
    { letter: 'त्र', name: 'Tra', instructions: 'Draw the combined conjunct form of त and र, then headline.' },
    { letter: 'ज्ञ', name: 'Gya', instructions: 'Draw the combined conjunct form of ज and ञ, then headline.' }
  ],
  ur: [
    { letter: 'ا', name: 'Alif', instructions: 'Draw a single straight vertical line from top to bottom.' },
    { letter: 'ب', name: 'Bey', instructions: 'Draw a boat/tray shape from right to left, place one dot below.' },
    { letter: 'پ', name: 'Pey', instructions: 'Draw a boat shape from right to left, place three dots below.' },
    { letter: 'ت', name: 'Tey', instructions: 'Draw a boat shape from right to left, place two dots above.' },
    { letter: 'ٹ', name: 'Tey (retroflex)', instructions: 'Draw a boat shape, place one dot above.' },
    { letter: 'ث', name: 'Sey', instructions: 'Draw a boat shape, place three dots above.' },
    { letter: 'ج', name: 'Jeem', instructions: 'Draw the open hook shape, place one dot inside the curve.' },
    { letter: 'چ', name: 'Chey', instructions: 'Draw the hook shape, place three dots inside the curve.' },
    { letter: 'ح', name: 'Haa', instructions: 'Draw the open hook shape with no dots.' },
    { letter: 'خ', name: 'Khey', instructions: 'Draw the hook shape, place one dot above.' },
    { letter: 'د', name: 'Daal', instructions: 'Draw a small curved stroke from right going left and down.' },
    { letter: 'ڈ', name: 'Daal (retroflex)', instructions: 'Draw Daal shape, place one dot above.' },
    { letter: 'ذ', name: 'Zaal', instructions: 'Draw Daal shape, place one dot above.' },
    { letter: 'ر', name: 'Rey', instructions: 'Draw a short curved stroke below the line.' },
    { letter: 'ڑ', name: 'Rey (retroflex)', instructions: 'Draw Rey shape, place one dot above.' },
    { letter: 'ز', name: 'Zey', instructions: 'Draw Rey shape, place one dot above.' },
    { letter: 'ژ', name: 'Zhey', instructions: 'Draw Rey shape, place three dots above.' },
    { letter: 'س', name: 'Seen', instructions: 'Draw three teeth/peaks in a wave, then a long tail.' },
    { letter: 'ش', name: 'Sheen', instructions: 'Draw three teeth like Seen, add three dots above.' },
    { letter: 'ص', name: 'Saad', instructions: 'Draw the closed oval with a flat tail extending right.' },
    { letter: 'ض', name: 'Zaad', instructions: 'Draw Saad shape, place one dot above.' },
    { letter: 'ط', name: 'Toey', instructions: 'Draw the tall loop with a flat base.' },
    { letter: 'ظ', name: 'Zoey', instructions: 'Draw Toey shape, place one dot above.' },
    { letter: 'ع', name: 'Ain', instructions: 'Draw the C-shaped hook opening upward.' },
    { letter: 'غ', name: 'Ghain', instructions: 'Draw Ain shape, place one dot above.' },
    { letter: 'ف', name: 'Fey', instructions: 'Draw the small loop at top with one dot inside, then descending tail.' },
    { letter: 'ق', name: 'Qaaf', instructions: 'Draw the loop with two dots above, then descending tail.' },
    { letter: 'ک', name: 'Kaaf', instructions: 'Draw the slanted stroke with the left-curving tail.' },
    { letter: 'گ', name: 'Gaaf', instructions: 'Draw Kaaf shape with an extra horizontal stroke.' },
    { letter: 'ل', name: 'Laam', instructions: 'Draw a tall vertical stroke curving at the bottom.' },
    { letter: 'م', name: 'Meem', instructions: 'Draw the small closed circle, then the tail going down.' },
    { letter: 'ن', name: 'Noon', instructions: 'Draw the boat/bowl shape, place one dot above.' },
    { letter: 'و', name: 'Wao', instructions: 'Draw the comma-like shape: a small head curving into a tail.' },
    { letter: 'ہ', name: 'Haa (Gol)', instructions: 'Draw the round do-chashmi shape.' },
    { letter: 'ھ', name: 'Do-chashmi Hey', instructions: 'Draw the double-eye (two small loops) shape.' },
    { letter: 'ی', name: 'Yey', instructions: 'Draw the boat shape with two dots below and a curving tail.' },
    { letter: 'ے', name: 'Bari Yey', instructions: 'Draw the deep swooping curve extending below the line.' }
  ],
  en: [
    { letter: 'A', name: 'A', instructions: 'Draw a left slant, a right slant meeting at top, then a horizontal bar across the middle.' },
    { letter: 'B', name: 'B', instructions: 'Draw a vertical line, then two bumps (loops) on the right — one on top, one on bottom.' },
    { letter: 'C', name: 'C', instructions: 'Draw a single open curve from top-right around to bottom-right.' },
    { letter: 'D', name: 'D', instructions: 'Draw a vertical line, then a large curved bump on the right.' },
    { letter: 'E', name: 'E', instructions: 'Draw a vertical line, then three horizontal lines: top, middle, bottom.' },
    { letter: 'F', name: 'F', instructions: 'Draw a vertical line, then two horizontal lines at the top and middle.' },
    { letter: 'G', name: 'G', instructions: 'Draw a C-curve, then add a small horizontal bar pointing inward at the middle-right.' },
    { letter: 'H', name: 'H', instructions: 'Draw two vertical lines side by side, connected by a horizontal bar in the middle.' },
    { letter: 'I', name: 'I', instructions: 'Draw a vertical line, with short horizontal bars at the top and bottom.' },
    { letter: 'J', name: 'J', instructions: 'Draw a top horizontal bar, a vertical line down, then curve it left at the bottom.' },
    { letter: 'K', name: 'K', instructions: 'Draw a vertical line, then two diagonal lines meeting it at the middle — one going up-right, one down-right.' },
    { letter: 'L', name: 'L', instructions: 'Draw a vertical line downward, then a horizontal line to the right at the bottom.' },
    { letter: 'M', name: 'M', instructions: 'Draw two vertical lines, connected at top by two diagonal strokes forming a V-shape.' },
    { letter: 'N', name: 'N', instructions: 'Draw a left vertical line, a diagonal going down to the right, then a right vertical line.' },
    { letter: 'O', name: 'O', instructions: 'Draw a smooth closed oval or circle.' },
    { letter: 'P', name: 'P', instructions: 'Draw a vertical line, then a curved bump (loop) at the top-right.' },
    { letter: 'Q', name: 'Q', instructions: 'Draw a circle, then add a small diagonal tail at the bottom-right.' },
    { letter: 'R', name: 'R', instructions: 'Draw a vertical line, a bump at the top-right, then a diagonal leg going down-right.' },
    { letter: 'S', name: 'S', instructions: 'Draw an S-curve: top curve going right, bottom curve going left.' },
    { letter: 'T', name: 'T', instructions: 'Draw a horizontal line at the top, then a vertical line down from its center.' },
    { letter: 'U', name: 'U', instructions: 'Draw a curve going down and then back up, like a horseshoe shape.' },
    { letter: 'V', name: 'V', instructions: 'Draw two diagonal lines meeting at a point at the bottom.' },
    { letter: 'W', name: 'W', instructions: 'Draw two V-shapes side by side, forming a zigzag pattern.' },
    { letter: 'X', name: 'X', instructions: 'Draw two diagonal lines crossing each other in the middle.' },
    { letter: 'Y', name: 'Y', instructions: 'Draw two diagonals meeting at a center point, then a vertical line going down.' },
    { letter: 'Z', name: 'Z', instructions: 'Draw a horizontal line at top, a diagonal going down-left, then a horizontal line at bottom.' }
  ],
  // Tamil (ta) — Vowels + Core Consonants
  ta: [
    { letter: 'அ', name: 'A', instructions: 'Draw the rounded body with a tail curving right.' },
    { letter: 'ஆ', name: 'Aa', instructions: 'Draw அ then add a vertical stroke on the right.' },
    { letter: 'இ', name: 'I', instructions: 'Draw a looped figure with two curves side by side.' },
    { letter: 'ஈ', name: 'Ii', instructions: 'Draw இ with an additional tail curving upward.' },
    { letter: 'உ', name: 'U', instructions: 'Draw a compact rounded loop.' },
    { letter: 'ஊ', name: 'Uu', instructions: 'Draw உ with a longer curving tail.' },
    { letter: 'எ', name: 'E', instructions: 'Draw the open curved shape leaning left.' },
    { letter: 'ஏ', name: 'Ee', instructions: 'Draw எ with a taller vertical stroke.' },
    { letter: 'ஐ', name: 'Ai', instructions: 'Draw the figure with two connecting curves.' },
    { letter: 'ஒ', name: 'O', instructions: 'Draw the rounded body with a dot or mark above.' },
    { letter: 'ஓ', name: 'Oo', instructions: 'Draw ஒ with an extended top stroke.' },
    { letter: 'ஔ', name: 'Au', instructions: 'Draw the complex double-curve figure.' },
    { letter: 'க', name: 'Ka', instructions: 'Draw the looping figure with a tail going right.' },
    { letter: 'ங', name: 'Nga', instructions: 'Draw the rounded loop with a descending tail.' },
    { letter: 'ச', name: 'Cha', instructions: 'Draw the compact curved shape.' },
    { letter: 'ஞ', name: 'Nya', instructions: 'Draw the double-curve body.' },
    { letter: 'ட', name: 'Ta', instructions: 'Draw the angular body with a right tail.' },
    { letter: 'ண', name: 'Na (hard)', instructions: 'Draw the rounded body with loops.' },
    { letter: 'த', name: 'Tha', instructions: 'Draw the open curved figure.' },
    { letter: 'ந', name: 'Na', instructions: 'Draw the looped body similar to ந shape.' },
    { letter: 'ப', name: 'Pa', instructions: 'Draw the angular shape with a right curve.' },
    { letter: 'ம', name: 'Ma', instructions: 'Draw the rounded closed loop figure.' },
    { letter: 'ய', name: 'Ya', instructions: 'Draw the flowing curved figure.' },
    { letter: 'ர', name: 'Ra', instructions: 'Draw the small curved stroke.' },
    { letter: 'ல', name: 'La', instructions: 'Draw the looped vertical figure.' },
    { letter: 'வ', name: 'Va', instructions: 'Draw the open curved body.' },
    { letter: 'ழ', name: 'Zha', instructions: 'Draw the unique Tamil curved shape.' },
    { letter: 'ள', name: 'La (hard)', instructions: 'Draw the rounded loop with a tail.' },
    { letter: 'ற', name: 'Ra (hard)', instructions: 'Draw the angular curved body.' },
    { letter: 'ன', name: 'Na (soft)', instructions: 'Draw the small looped curve.' }
  ],
  // Telugu (te) — Vowels + Core Consonants
  te: [
    { letter: 'అ', name: 'A', instructions: 'Draw the rounded top loop with a descending tail.' },
    { letter: 'ఆ', name: 'Aa', instructions: 'Draw అ then add a vertical stroke on the right.' },
    { letter: 'ఇ', name: 'I', instructions: 'Draw the looped body curving right.' },
    { letter: 'ఈ', name: 'Ii', instructions: 'Draw ఇ with an extended tail.' },
    { letter: 'ఉ', name: 'U', instructions: 'Draw the compact curved loop.' },
    { letter: 'ఊ', name: 'Uu', instructions: 'Draw ఉ with a longer extension.' },
    { letter: 'ఎ', name: 'E', instructions: 'Draw the rounded body with a left curve.' },
    { letter: 'ఏ', name: 'Ee', instructions: 'Draw ఎ with a taller top stroke.' },
    { letter: 'ఐ', name: 'Ai', instructions: 'Draw the double-loop figure.' },
    { letter: 'ఒ', name: 'O', instructions: 'Draw the rounded body with a mark above.' },
    { letter: 'ఓ', name: 'Oo', instructions: 'Draw ఒ with an extended stroke.' },
    { letter: 'ఔ', name: 'Au', instructions: 'Draw the complex rounded figure.' },
    { letter: 'క', name: 'Ka', instructions: 'Draw the rounded loop with the right tail.' },
    { letter: 'ఖ', name: 'Kha', instructions: 'Draw the double-loop figure.' },
    { letter: 'గ', name: 'Ga', instructions: 'Draw the curved body with descending stroke.' },
    { letter: 'ఘ', name: 'Gha', instructions: 'Draw the complex rounded loops.' },
    { letter: 'చ', name: 'Cha', instructions: 'Draw the angular body curving right.' },
    { letter: 'జ', name: 'Ja', instructions: 'Draw the looped body with a tail.' },
    { letter: 'ట', name: 'Ta', instructions: 'Draw the rounded body with descending stroke.' },
    { letter: 'డ', name: 'Da', instructions: 'Draw the curved figure with a loop.' },
    { letter: 'ణ', name: 'Na (hard)', instructions: 'Draw the complex loop with a tail.' },
    { letter: 'త', name: 'Tha', instructions: 'Draw the open curved figure.' },
    { letter: 'ద', name: 'Da (soft)', instructions: 'Draw the rounded open shape.' },
    { letter: 'న', name: 'Na', instructions: 'Draw the looped body curving down.' },
    { letter: 'ప', name: 'Pa', instructions: 'Draw the angular shape with a right curve.' },
    { letter: 'బ', name: 'Ba', instructions: 'Draw the rounded loop figure.' },
    { letter: 'మ', name: 'Ma', instructions: 'Draw the compact rounded body.' },
    { letter: 'య', name: 'Ya', instructions: 'Draw the flowing curved figure.' },
    { letter: 'ర', name: 'Ra', instructions: 'Draw the small angular stroke.' },
    { letter: 'ల', name: 'La', instructions: 'Draw the looped vertical figure.' },
    { letter: 'వ', name: 'Va', instructions: 'Draw the open curved body.' },
    { letter: 'శ', name: 'Sha', instructions: 'Draw the complex loop figure.' },
    { letter: 'ష', name: 'Sha (hard)', instructions: 'Draw the angular loop body.' },
    { letter: 'స', name: 'Sa', instructions: 'Draw the flowing S-like curve.' },
    { letter: 'హ', name: 'Ha', instructions: 'Draw the rounded body with right loops.' }
  ],
  // Bengali (bn) — Vowels + Core Consonants
  bn: [
    { letter: 'অ', name: 'A', instructions: 'Draw the rounded body with a matra on top.' },
    { letter: 'আ', name: 'Aa', instructions: 'Draw অ then add a vertical stroke on the right.' },
    { letter: 'ই', name: 'I', instructions: 'Draw the looped figure with the headline.' },
    { letter: 'ঈ', name: 'Ii', instructions: 'Draw ই with a longer tail.' },
    { letter: 'উ', name: 'U', instructions: 'Draw the curved hook shape.' },
    { letter: 'ঊ', name: 'Uu', instructions: 'Draw উ with a deeper hook.' },
    { letter: 'এ', name: 'E', instructions: 'Draw the triangular shape with headline.' },
    { letter: 'ঐ', name: 'Oi', instructions: 'Draw the double-stroke figure.' },
    { letter: 'ও', name: 'O', instructions: 'Draw the looped figure with side strokes.' },
    { letter: 'ঔ', name: 'Ou', instructions: 'Draw the complex combined figure.' },
    { letter: 'ক', name: 'Ka', instructions: 'Draw the vertical line with a right-curving loop, then headline.' },
    { letter: 'খ', name: 'Kha', instructions: 'Draw the double-loop body with headline.' },
    { letter: 'গ', name: 'Ga', instructions: 'Draw the curved stroke hooking left, then headline.' },
    { letter: 'ঘ', name: 'Gha', instructions: 'Draw the loop with a vertical body, then headline.' },
    { letter: 'চ', name: 'Cha', instructions: 'Draw the curved top with vertical stroke, then headline.' },
    { letter: 'ছ', name: 'Chha', instructions: 'Draw the distinctive body, then headline.' },
    { letter: 'জ', name: 'Ja', instructions: 'Draw the hook figure with headline.' },
    { letter: 'ঝ', name: 'Jha', instructions: 'Draw the cross strokes with tails, then headline.' },
    { letter: 'ট', name: 'Ta (hard)', instructions: 'Draw the curved cap and downward stroke, then headline.' },
    { letter: 'ঠ', name: 'Tha (hard)', instructions: 'Draw the circular loop, then headline.' },
    { letter: 'ড', name: 'Da (hard)', instructions: 'Draw the top curve and descending stroke, then headline.' },
    { letter: 'ঢ', name: 'Dha (hard)', instructions: 'Draw the round loop with descending tail, then headline.' },
    { letter: 'ণ', name: 'Na (hard)', instructions: 'Draw the complex body with loops, then headline.' },
    { letter: 'ত', name: 'Ta', instructions: 'Draw the curved body, then headline.' },
    { letter: 'থ', name: 'Tha', instructions: 'Draw the circular loop and stroke, then headline.' },
    { letter: 'দ', name: 'Da', instructions: 'Draw the rounded body, then headline.' },
    { letter: 'ধ', name: 'Dha', instructions: 'Draw the curved body, then headline.' },
    { letter: 'ন', name: 'Na', instructions: 'Draw the vertical strokes with bottom curve, then headline.' },
    { letter: 'প', name: 'Pa', instructions: 'Draw the vertical and right-curving loop, then headline.' },
    { letter: 'ফ', name: 'Pha', instructions: 'Draw the central loop, then headline.' },
    { letter: 'ব', name: 'Ba', instructions: 'Draw the left-loop body, then headline.' },
    { letter: 'ভ', name: 'Bha', instructions: 'Draw the rounded body, then headline.' },
    { letter: 'ম', name: 'Ma', instructions: 'Draw the vertical with bottom loop, then headline.' },
    { letter: 'য', name: 'Ya', instructions: 'Draw the flowing figure, then headline.' },
    { letter: 'র', name: 'Ra', instructions: 'Draw the small curving stroke below headline.' },
    { letter: 'ল', name: 'La', instructions: 'Draw the vertical with bottom-left curve, then headline.' },
    { letter: 'শ', name: 'Sha', instructions: 'Draw the three vertical strokes, then headline.' },
    { letter: 'ষ', name: 'Sha (hard)', instructions: 'Draw the complex loop body, then headline.' },
    { letter: 'স', name: 'Sa', instructions: 'Draw the flowing curve, then headline.' },
    { letter: 'হ', name: 'Ha', instructions: 'Draw the distinctive right-side loops, then headline.' }
  ],
  // Marathi (mr) — same script as Hindi (Devanagari) with some additions
  mr: [
    { letter: 'अ', name: 'A', instructions: 'Draw the vertical line, curved stroke on top, then headline.' },
    { letter: 'आ', name: 'Aa', instructions: 'Start like अ, add a right vertical line.' },
    { letter: 'इ', name: 'I', instructions: 'Draw two curves and a vertical line with headline.' },
    { letter: 'ई', name: 'Ee', instructions: 'Draw the vertical with a long curve below headline.' },
    { letter: 'उ', name: 'U', instructions: 'Draw the curved hook below headline.' },
    { letter: 'ऊ', name: 'Oo', instructions: 'Draw a deeper curved hook.' },
    { letter: 'ए', name: 'E', instructions: 'Draw the left triangle, vertical line, headline.' },
    { letter: 'ऐ', name: 'Ai', instructions: 'Like ए with an extra caret above.' },
    { letter: 'ओ', name: 'O', instructions: 'Draw अ with ा matra and ो hook.' },
    { letter: 'औ', name: 'Au', instructions: 'Like ओ with an extra caret above.' },
    { letter: 'क', name: 'Ka', instructions: 'Draw the center loop curving right, then headline.' },
    { letter: 'ख', name: 'Kha', instructions: 'Draw the vertical, right-side loop, headline.' },
    { letter: 'ग', name: 'Ga', instructions: 'Draw a curved stroke hooking left, headline.' },
    { letter: 'घ', name: 'Gha', instructions: 'Draw top loop, vertical body, bottom hook, headline.' },
    { letter: 'च', name: 'Cha', instructions: 'Draw curved top, vertical stroke, headline.' },
    { letter: 'छ', name: 'Chha', instructions: 'Draw the double-loop body, headline.' },
    { letter: 'ज', name: 'Ja', instructions: 'Draw vertical with left-curving hook, headline.' },
    { letter: 'झ', name: 'Jha', instructions: 'Draw cross strokes with curved tails, headline.' },
    { letter: 'ट', name: 'Ta (hard)', instructions: 'Draw curved cap and downward stroke, headline.' },
    { letter: 'ठ', name: 'Tha (hard)', instructions: 'Draw circular loop and vertical tail, headline.' },
    { letter: 'ड', name: 'Da (hard)', instructions: 'Draw top curve and descending stroke, headline.' },
    { letter: 'ढ', name: 'Dha (hard)', instructions: 'Draw round loop with descending tail, headline.' },
    { letter: 'ण', name: 'Na (hard)', instructions: 'Draw the complex body with loops, headline.' },
    { letter: 'त', name: 'Ta', instructions: 'Draw horizontal line curling downward, headline.' },
    { letter: 'थ', name: 'Tha', instructions: 'Draw circular loop and vertical stroke, headline.' },
    { letter: 'द', name: 'Da', instructions: 'Draw rounded body opening left, headline.' },
    { letter: 'ध', name: 'Dha', instructions: 'Draw curved body with right-side vertical, headline.' },
    { letter: 'न', name: 'Na', instructions: 'Draw left vertical, bottom curve, right vertical, headline.' },
    { letter: 'प', name: 'Pa', instructions: 'Draw vertical and right-curving loop, headline.' },
    { letter: 'फ', name: 'Pha', instructions: 'Draw central loop and side strokes, headline.' },
    { letter: 'ब', name: 'Ba', instructions: 'Draw vertical with left-side loop, headline.' },
    { letter: 'भ', name: 'Bha', instructions: 'Draw rounded body with central stroke, headline.' },
    { letter: 'म', name: 'Ma', instructions: 'Draw vertical, bottom loop, horizontal bar, headline.' },
    { letter: 'य', name: 'Ya', instructions: 'Draw two-loop figure flowing right, headline.' },
    { letter: 'र', name: 'Ra', instructions: 'Draw small left-curving stroke below headline.' },
    { letter: 'ल', name: 'La', instructions: 'Draw vertical with bottom-left curve, headline.' },
    { letter: 'व', name: 'Va', instructions: 'Draw open loop curving right, headline.' },
    { letter: 'श', name: 'Sha', instructions: 'Draw three vertical strokes with headline.' },
    { letter: 'ष', name: 'Sha (hard)', instructions: 'Draw complex loop body under headline.' },
    { letter: 'स', name: 'Sa', instructions: 'Draw flowing S-like curve, headline.' },
    { letter: 'ह', name: 'Ha', instructions: 'Draw vertical with right-side loops, headline.' },
    { letter: 'ळ', name: 'La (Marathi)', instructions: 'Draw the unique Marathi ळ with curved loop, headline.' }
  ],
  // Marwadi (mwr) — Uses Devanagari script, same as Hindi
  mwr: [
    { letter: 'अ', name: 'A', instructions: 'Draw the vertical line, curved stroke on top, then headline.' },
    { letter: 'आ', name: 'Aa', instructions: 'Start like अ, add a right vertical line.' },
    { letter: 'इ', name: 'I', instructions: 'Draw two curves and a vertical with headline.' },
    { letter: 'ई', name: 'Ee', instructions: 'Draw vertical with a long curve below headline.' },
    { letter: 'उ', name: 'U', instructions: 'Draw the curved hook below headline.' },
    { letter: 'ऊ', name: 'Oo', instructions: 'Draw a deeper curved hook.' },
    { letter: 'ए', name: 'E', instructions: 'Draw the left triangle, vertical line, headline.' },
    { letter: 'ऐ', name: 'Ai', instructions: 'Like ए with extra caret above.' },
    { letter: 'ओ', name: 'O', instructions: 'Draw अ with ा matra and ो hook.' },
    { letter: 'औ', name: 'Au', instructions: 'Like ओ with extra caret above.' },
    { letter: 'क', name: 'Ka', instructions: 'Draw center loop curving right, headline.' },
    { letter: 'ख', name: 'Kha', instructions: 'Draw vertical, right-side loop, headline.' },
    { letter: 'ग', name: 'Ga', instructions: 'Draw curved stroke hooking left, headline.' },
    { letter: 'घ', name: 'Gha', instructions: 'Draw top loop, vertical body, bottom hook, headline.' },
    { letter: 'च', name: 'Cha', instructions: 'Draw curved top, vertical stroke, headline.' },
    { letter: 'छ', name: 'Chha', instructions: 'Draw double-loop body, headline.' },
    { letter: 'ज', name: 'Ja', instructions: 'Draw vertical with left-curving hook, headline.' },
    { letter: 'झ', name: 'Jha', instructions: 'Draw cross strokes with curved tails, headline.' },
    { letter: 'ट', name: 'Ta (hard)', instructions: 'Draw curved cap and downward stroke, headline.' },
    { letter: 'ठ', name: 'Tha (hard)', instructions: 'Draw circular loop and vertical tail, headline.' },
    { letter: 'ड', name: 'Da (hard)', instructions: 'Draw top curve and descending stroke, headline.' },
    { letter: 'ढ', name: 'Dha (hard)', instructions: 'Draw round loop with descending tail, headline.' },
    { letter: 'ण', name: 'Na (hard)', instructions: 'Draw complex body with loops, headline.' },
    { letter: 'त', name: 'Ta', instructions: 'Draw horizontal line curling downward, headline.' },
    { letter: 'थ', name: 'Tha', instructions: 'Draw circular loop and vertical stroke, headline.' },
    { letter: 'द', name: 'Da', instructions: 'Draw rounded body opening left, headline.' },
    { letter: 'ध', name: 'Dha', instructions: 'Draw curved body with right-side vertical, headline.' },
    { letter: 'न', name: 'Na', instructions: 'Draw left vertical, bottom curve, right vertical, headline.' },
    { letter: 'प', name: 'Pa', instructions: 'Draw vertical and right-curving loop, headline.' },
    { letter: 'फ', name: 'Pha', instructions: 'Draw central loop and side strokes, headline.' },
    { letter: 'ब', name: 'Ba', instructions: 'Draw vertical with left-side loop, headline.' },
    { letter: 'भ', name: 'Bha', instructions: 'Draw rounded body with central stroke, headline.' },
    { letter: 'म', name: 'Ma', instructions: 'Draw vertical, bottom loop, horizontal bar, headline.' },
    { letter: 'य', name: 'Ya', instructions: 'Draw two-loop figure flowing right, headline.' },
    { letter: 'र', name: 'Ra', instructions: 'Draw small left-curving stroke below headline.' },
    { letter: 'ल', name: 'La', instructions: 'Draw vertical with bottom-left curve, headline.' },
    { letter: 'व', name: 'Va', instructions: 'Draw open loop curving right, headline.' },
    { letter: 'श', name: 'Sha', instructions: 'Draw three vertical strokes with headline.' },
    { letter: 'स', name: 'Sa', instructions: 'Draw flowing S-like curve, headline.' },
    { letter: 'ह', name: 'Ha', instructions: 'Draw vertical with right-side loops, headline.' }
  ]
};

// ============================================================
// VOCABULARY WORDS — Word, Meaning, Example per letter per language
// ============================================================
export const VOCAB_WORDS = {
  en: {
    'A': { word: 'Accomplish', meaning: 'To achieve or complete successfully', example: 'She worked hard to accomplish her goals.' },
    'B': { word: 'Benevolent', meaning: 'Kind and generous', example: 'The benevolent teacher helped every student.' },
    'C': { word: 'Courage', meaning: 'Bravery in facing difficulty', example: 'It takes courage to speak the truth.' },
    'D': { word: 'Diligent', meaning: 'Hardworking and careful', example: 'A diligent student always does well in exams.' },
    'E': { word: 'Empathy', meaning: 'Understanding others\' feelings', example: 'Empathy helps us build strong relationships.' },
    'F': { word: 'Flourish', meaning: 'To grow or develop well', example: 'Plants flourish in sunlight and water.' },
    'G': { word: 'Gratitude', meaning: 'Feeling of being thankful', example: 'She expressed gratitude for the help she received.' },
    'H': { word: 'Harmony', meaning: 'A state of peace and agreement', example: 'They lived in harmony with nature.' },
    'I': { word: 'Inspire', meaning: 'To motivate or encourage', example: 'Great leaders inspire people around them.' },
    'J': { word: 'Jubilant', meaning: 'Extremely happy and joyful', example: 'The team was jubilant after winning the match.' },
    'K': { word: 'Keen', meaning: 'Eager or enthusiastic', example: 'She was keen to learn new languages.' },
    'L': { word: 'Luminous', meaning: 'Bright or shining', example: 'The luminous stars lit up the night sky.' },
    'M': { word: 'Magnificent', meaning: 'Extremely beautiful or grand', example: 'The Taj Mahal is a magnificent monument.' },
    'N': { word: 'Nurture', meaning: 'To care for and help grow', example: 'Parents nurture their children with love.' },
    'O': { word: 'Optimistic', meaning: 'Hopeful about the future', example: 'She remained optimistic despite the challenges.' },
    'P': { word: 'Persevere', meaning: 'To continue despite difficulty', example: 'You must persevere to achieve your dreams.' },
    'Q': { word: 'Quest', meaning: 'A long search for something', example: 'The scientist began a quest for a cure.' },
    'R': { word: 'Resilient', meaning: 'Able to recover from setbacks', example: 'Resilient people bounce back from failure.' },
    'S': { word: 'Serenity', meaning: 'A state of calm and peace', example: 'The lake brought a sense of serenity.' },
    'T': { word: 'Tenacious', meaning: 'Persistent and determined', example: 'Her tenacious spirit helped her succeed.' },
    'U': { word: 'Unique', meaning: 'One of a kind, unlike anything else', example: 'Every person has a unique fingerprint.' },
    'V': { word: 'Versatile', meaning: 'Able to adapt to many functions', example: 'She is a versatile artist who paints and sculpts.' },
    'W': { word: 'Wisdom', meaning: 'Deep knowledge and good judgement', example: 'With age comes wisdom and experience.' },
    'X': { word: 'Xenial', meaning: 'Hospitable and welcoming', example: 'The xenial host made everyone feel at home.' },
    'Y': { word: 'Yearn', meaning: 'To desire or long for something', example: 'He yearned to travel the world.' },
    'Z': { word: 'Zealous', meaning: 'Full of passion and enthusiasm', example: 'The zealous volunteer worked tirelessly.' }
  },
  hi: {
    'अ': { word: 'अनार (Anaar)', meaning: 'Pomegranate — a red fruit', example: 'अनार खाने से खून बढ़ता है।' },
    'आ': { word: 'आम (Aam)', meaning: 'Mango — king of fruits', example: 'आम गर्मियों का फल है।' },
    'इ': { word: 'इमली (Imli)', meaning: 'Tamarind — a sour fruit', example: 'इमली का स्वाद खट्टा होता है।' },
    'ई': { word: 'ईख (Eekh)', meaning: 'Sugarcane', example: 'ईख से चीनी बनाई जाती है।' },
    'उ': { word: 'उल्लू (Ullu)', meaning: 'Owl — a nocturnal bird', example: 'उल्लू रात में जागता है।' },
    'ऊ': { word: 'ऊन (Oon)', meaning: 'Wool — used for warm clothes', example: 'ऊन से स्वेटर बनाते हैं।' },
    'ए': { word: 'एकता (Ekta)', meaning: 'Unity — togetherness', example: 'एकता में बल है।' },
    'ऐ': { word: 'ऐनक (Ainak)', meaning: 'Spectacles — eyeglasses', example: 'दादाजी ऐनक लगाकर पढ़ते हैं।' },
    'ओ': { word: 'ओखली (Okhli)', meaning: 'Mortar — grinding bowl', example: 'ओखली में मसाले कूटते हैं।' },
    'औ': { word: 'औरत (Aurat)', meaning: 'Woman', example: 'हर औरत सम्मान की हकदार है।' },
    'अं': { word: 'अंगूर (Angoor)', meaning: 'Grapes', example: 'अंगूर बहुत मीठे हैं।' },
    'अः': { word: 'अतः (Atah)', meaning: 'Therefore / Hence', example: 'वह बीमार था, अतः नहीं आया।' },
    'क': { word: 'कमल (Kamal)', meaning: 'Lotus — national flower of India', example: 'कमल पानी में खिलता है।' },
    'ख': { word: 'खरगोश (Khargosh)', meaning: 'Rabbit', example: 'खरगोश बहुत तेज़ दौड़ता है।' },
    'ग': { word: 'गमला (Gamla)', meaning: 'Flower pot', example: 'गमले में सुंदर फूल लगे हैं।' },
    'घ': { word: 'घड़ी (Ghadi)', meaning: 'Clock / Watch', example: 'घड़ी में दस बज रहे हैं।' },
    'ङ': { word: 'पतंग (Patang)', meaning: 'Kite (uses ङ sound)', example: 'बच्चे पतंग उड़ा रहे हैं।' },
    'च': { word: 'चम्मच (Chammach)', meaning: 'Spoon', example: 'चम्मच से खाना खाओ।' },
    'छ': { word: 'छाता (Chhata)', meaning: 'Umbrella', example: 'बारिश में छाता ले जाओ।' },
    'ज': { word: 'जहाज़ (Jahaaz)', meaning: 'Ship / Airplane', example: 'जहाज़ आसमान में उड़ रहा है।' },
    'झ': { word: 'झंडा (Jhanda)', meaning: 'Flag', example: 'तिरंगा झंडा हमारा गौरव है।' },
    'ञ': { word: 'विज्ञान (Vigyan)', meaning: 'Science (uses ञ sound)', example: 'विज्ञान से आविष्कार होते हैं।' },
    'ट': { word: 'टमाटर (Tamatar)', meaning: 'Tomato', example: 'टमाटर लाल और गोल होता है।' },
    'ठ': { word: 'ठंड (Thand)', meaning: 'Cold weather', example: 'सर्दियों में बहुत ठंड पड़ती है।' },
    'ड': { word: 'डमरू (Damru)', meaning: 'Small drum of Shiva', example: 'शिवजी डमरू बजाते हैं।' },
    'ढ': { word: 'ढोल (Dhol)', meaning: 'Drum — big musical drum', example: 'शादी में ढोल बजता है।' },
    'ण': { word: 'गुण (Gun)', meaning: 'Quality / Virtue', example: 'अच्छे गुण अपनाओ।' },
    'त': { word: 'तारा (Taara)', meaning: 'Star', example: 'रात में तारे चमकते हैं।' },
    'थ': { word: 'थाली (Thali)', meaning: 'Plate — eating plate', example: 'थाली में खाना परोसो।' },
    'द': { word: 'दवाई (Dawai)', meaning: 'Medicine', example: 'बीमार होने पर दवाई खाओ।' },
    'ध': { word: 'धनुष (Dhanush)', meaning: 'Bow — archery bow', example: 'राम ने धनुष उठाया।' },
    'न': { word: 'नदी (Nadi)', meaning: 'River', example: 'गंगा एक पवित्र नदी है।' },
    'प': { word: 'पतंग (Patang)', meaning: 'Kite', example: 'बच्चे पतंग उड़ाते हैं।' },
    'फ': { word: 'फूल (Phool)', meaning: 'Flower', example: 'बगीचे में सुंदर फूल खिले हैं।' },
    'ब': { word: 'बादल (Baadal)', meaning: 'Cloud', example: 'आसमान में बादल छाए हैं।' },
    'भ': { word: 'भालू (Bhalu)', meaning: 'Bear', example: 'भालू जंगल में रहता है।' },
    'म': { word: 'मोर (Mor)', meaning: 'Peacock — national bird of India', example: 'मोर बारिश में नाचता है।' },
    'य': { word: 'यात्रा (Yatra)', meaning: 'Journey / Travel', example: 'हमने पहाड़ों की यात्रा की।' },
    'र': { word: 'रंग (Rang)', meaning: 'Color', example: 'इंद्रधनुष में सात रंग होते हैं।' },
    'ल': { word: 'लड़की (Ladki)', meaning: 'Girl', example: 'वह लड़की बहुत होशियार है।' },
    'व': { word: 'वन (Van)', meaning: 'Forest', example: 'वन में बहुत से जानवर रहते हैं।' },
    'श': { word: 'शेर (Sher)', meaning: 'Lion', example: 'शेर जंगल का राजा है।' },
    'ष': { word: 'षट्कोण (Shatkon)', meaning: 'Hexagon — six-sided shape', example: 'मधुमक्खी का छत्ता षट्कोण होता है।' },
    'स': { word: 'सूरज (Suraj)', meaning: 'Sun', example: 'सूरज पूरब में उगता है।' },
    'ह': { word: 'हाथी (Haathi)', meaning: 'Elephant', example: 'हाथी सबसे बड़ा जानवर है।' },
    'क्ष': { word: 'क्षमा (Kshama)', meaning: 'Forgiveness', example: 'क्षमा माँगना बड़ों का गुण है।' },
    'त्र': { word: 'त्रिशूल (Trishul)', meaning: 'Trident — weapon of Shiva', example: 'शिवजी का त्रिशूल प्रसिद्ध है।' },
    'ज्ञ': { word: 'ज्ञान (Gyaan)', meaning: 'Knowledge / Wisdom', example: 'ज्ञान सबसे बड़ा धन है।' }
  },
  ur: {
    'ا': { word: 'انار (Anaar)', meaning: 'Pomegranate', example: 'انار صحت کے لیے اچھا ہے۔' },
    'ب': { word: 'بلی (Billi)', meaning: 'Cat', example: 'بلی دودھ پیتی ہے۔' },
    'پ': { word: 'پانی (Paani)', meaning: 'Water', example: 'پانی زندگی کے لیے ضروری ہے۔' },
    'ت': { word: 'تارا (Taara)', meaning: 'Star', example: 'رات کو تارے چمکتے ہیں۔' },
    'ٹ': { word: 'ٹوپی (Topi)', meaning: 'Cap / Hat', example: 'سردیوں میں ٹوپی پہنو۔' },
    'ث': { word: 'ثمر (Samar)', meaning: 'Fruit / Result', example: 'محنت کا ثمر ضرور ملتا ہے۔' },
    'ج': { word: 'جہاز (Jahaaz)', meaning: 'Ship / Airplane', example: 'جہاز آسمان میں اڑتا ہے۔' },
    'چ': { word: 'چاند (Chaand)', meaning: 'Moon', example: 'آج چاند بہت خوبصورت ہے۔' },
    'ح': { word: 'حکمت (Hikmat)', meaning: 'Wisdom', example: 'حکمت سے کام لو۔' },
    'خ': { word: 'خط (Khat)', meaning: 'Letter / Line', example: 'اسے خط لکھو۔' },
    'د': { word: 'دریا (Darya)', meaning: 'River', example: 'دریا میں پانی بہتا ہے۔' },
    'ڈ': { word: 'ڈبہ (Dabba)', meaning: 'Box / Container', example: 'کھانا ڈبے میں رکھو۔' },
    'ذ': { word: 'ذہن (Zehan)', meaning: 'Mind / Intellect', example: 'اس کا ذہن بہت تیز ہے۔' },
    'ر': { word: 'رنگ (Rang)', meaning: 'Color', example: 'قوس قزح میں سات رنگ ہیں۔' },
    'ڑ': { word: 'پہاڑ (Pahaad)', meaning: 'Mountain', example: 'پہاڑ بہت اونچے ہیں۔' },
    'ز': { word: 'زمین (Zameen)', meaning: 'Earth / Land', example: 'زمین گول ہے۔' },
    'ژ': { word: 'ژالہ (Zhala)', meaning: 'Hailstorm', example: 'آج ژالہ باری ہوئی۔' },
    'س': { word: 'ستارہ (Sitaara)', meaning: 'Star', example: 'ستارے رات کو چمکتے ہیں۔' },
    'ش': { word: 'شیر (Sher)', meaning: 'Lion', example: 'شیر جنگل کا بادشاہ ہے۔' },
    'ص': { word: 'صبر (Sabr)', meaning: 'Patience', example: 'صبر کا پھل میٹھا ہوتا ہے۔' },
    'ض': { word: 'ضرورت (Zaroorat)', meaning: 'Need / Necessity', example: 'پانی ایک ضرورت ہے۔' },
    'ط': { word: 'طوطا (Tota)', meaning: 'Parrot', example: 'طوطا سبز رنگ کا ہوتا ہے۔' },
    'ظ': { word: 'ظالم (Zaalim)', meaning: 'Cruel / Tyrant', example: 'ظالم سے ڈرو نہیں۔' },
    'ع': { word: 'عقل (Aqal)', meaning: 'Wisdom / Intellect', example: 'عقل سے کام لو۔' },
    'غ': { word: 'غصہ (Gussa)', meaning: 'Anger', example: 'غصہ صحت کے لیے برا ہے۔' },
    'ف': { word: 'فجر (Fajr)', meaning: 'Dawn / Morning prayer', example: 'فجر کی نماز پڑھو۔' },
    'ق': { word: 'قلم (Qalam)', meaning: 'Pen', example: 'قلم تلوار سے طاقتور ہے۔' },
    'ک': { word: 'کتاب (Kitaab)', meaning: 'Book', example: 'کتاب پڑھنا اچھی عادت ہے۔' },
    'گ': { word: 'گلاب (Gulaab)', meaning: 'Rose', example: 'گلاب خوشبودار پھول ہے۔' },
    'ل': { word: 'لکھنا (Likhna)', meaning: 'To write', example: 'خط لکھنا سیکھو۔' },
    'م': { word: 'مدرسہ (Madrasa)', meaning: 'School', example: 'مدرسے میں علم حاصل کرو۔' },
    'ن': { word: 'نماز (Namaaz)', meaning: 'Prayer', example: 'نماز وقت پر پڑھو۔' },
    'و': { word: 'وطن (Watan)', meaning: 'Homeland', example: 'وطن سے محبت کرو۔' },
    'ہ': { word: 'ہاتھی (Haathi)', meaning: 'Elephant', example: 'ہاتھی سب سے بڑا جانور ہے۔' },
    'ھ': { word: 'پھول (Phool)', meaning: 'Flower (uses ھ sound)', example: 'پھول باغ میں کھلتے ہیں۔' },
    'ی': { word: 'یاد (Yaad)', meaning: 'Memory / Remembrance', example: 'پرانے دن یاد آتے ہیں۔' },
    'ے': { word: 'گھر جائے (Ghar jaaye)', meaning: 'Should go home (uses ے)', example: 'وہ گھر جائے۔' }
  },
  // Tamil vocabulary
  ta: {
    'அ': { word: 'அம்மா (Amma)', meaning: 'Mother', example: 'அம்மா சமையல் செய்கிறாள்.' },
    'ஆ': { word: 'ஆறு (Aaru)', meaning: 'River', example: 'ஆறு கடலில் கலக்கிறது.' },
    'இ': { word: 'இலை (Ilai)', meaning: 'Leaf', example: 'மரத்தில் இலை பச்சையாக உள்ளது.' },
    'ஈ': { word: 'ஈ (Ee)', meaning: 'Fly — insect', example: 'ஈ உணவின் மீது அமர்ந்தது.' },
    'உ': { word: 'உணவு (Unavu)', meaning: 'Food', example: 'சத்தான உணவு சாப்பிடுங்கள்.' },
    'ஊ': { word: 'ஊர் (Oor)', meaning: 'Village / Town', example: 'என் ஊர் மிகவும் அழகு.' },
    'எ': { word: 'எலி (Eli)', meaning: 'Rat', example: 'எலி பூனையிடம் இருந்து ஓடியது.' },
    'ஏ': { word: 'ஏணி (Eni)', meaning: 'Ladder', example: 'ஏணி வைத்து மேலே ஏறினான்.' },
    'ஐ': { word: 'ஐந்து (Ainthu)', meaning: 'Five (number)', example: 'எனக்கு ஐந்து புத்தகங்கள் உள்ளன.' },
    'ஒ': { word: 'ஒட்டகம் (Ottakam)', meaning: 'Camel', example: 'ஒட்டகம் பாலைவனத்தில் வாழும்.' },
    'ஓ': { word: 'ஓடு (Odu)', meaning: 'Run / Tile', example: 'வேகமாக ஓடு!' },
    'ஔ': { word: 'ஔவையார் (Avvaiyar)', meaning: 'Ancient Tamil poetess', example: 'ஔவையார் சிறந்த கவிஞர்.' },
    'க': { word: 'கடல் (Kadal)', meaning: 'Sea / Ocean', example: 'கடல் மிகப்பெரியது.' },
    'ங': { word: 'மாங்காய் (Mangai)', meaning: 'Raw mango (uses ங)', example: 'மாங்காய் புளிப்பாக இருக்கும்.' },
    'ச': { word: 'சந்திரன் (Chandhiran)', meaning: 'Moon', example: 'சந்திரன் இரவில் ஒளிர்கிறான்.' },
    'ஞ': { word: 'ஞானம் (Gyanam)', meaning: 'Wisdom / Knowledge', example: 'ஞானம் பெறுவது உயர்ந்தது.' },
    'ட': { word: 'டாக்டர் (Doctor)', meaning: 'Doctor', example: 'டாக்டர் நோயாளிகளுக்கு உதவுகிறார்.' },
    'ண': { word: 'மணி (Mani)', meaning: 'Bell / Gem', example: 'கோயில் மணி ஒலிக்கிறது.' },
    'த': { word: 'தாமரை (Taamarai)', meaning: 'Lotus', example: 'தாமரை குளத்தில் மலர்கிறது.' },
    'ந': { word: 'நதி (Nadhi)', meaning: 'River', example: 'நதி ஓயாமல் ஓடுகிறது.' },
    'ப': { word: 'பறவை (Paravai)', meaning: 'Bird', example: 'பறவை வானில் பறக்கிறது.' },
    'ம': { word: 'மலர் (Malar)', meaning: 'Flower', example: 'மலர் நல்ல வாசனை தருகிறது.' },
    'ய': { word: 'யானை (Yanai)', meaning: 'Elephant', example: 'யானை மிகப்பெரிய விலங்கு.' },
    'ர': { word: 'ரயில் (Rail)', meaning: 'Train', example: 'ரயில் நிலையத்தில் நிற்கிறது.' },
    'ல': { word: 'லட்டு (Laddu)', meaning: 'Laddu — sweet ball', example: 'லட்டு மிகவும் சுவையானது.' },
    'வ': { word: 'வானம் (Vaanam)', meaning: 'Sky', example: 'வானம் நீல நிறமாக உள்ளது.' },
    'ழ': { word: 'தமிழ் (Tamil)', meaning: 'Tamil language', example: 'தமிழ் மிகப்பழமையான மொழி.' },
    'ள': { word: 'விளக்கு (Vilakku)', meaning: 'Lamp', example: 'விளக்கு ஒளியை தருகிறது.' },
    'ற': { word: 'கற்றல் (Katral)', meaning: 'Learning', example: 'கற்றல் வாழ்வில் முக்கியம்.' },
    'ன': { word: 'மனம் (Manam)', meaning: 'Mind / Heart', example: 'நல்ல மனம் இருக்க வேண்டும்.' }
  },
  // Telugu vocabulary
  te: {
    'అ': { word: 'అమ్మ (Amma)', meaning: 'Mother', example: 'అమ్మ వంట చేస్తుంది.' },
    'ఆ': { word: 'ఆకాశం (Aakaasham)', meaning: 'Sky', example: 'ఆకాశం నీలంగా ఉంది.' },
    'ఇ': { word: 'ఇల్లు (Illu)', meaning: 'House', example: 'ఇల్లు చాలా అందంగా ఉంది.' },
    'ఈ': { word: 'ఈగ (Eega)', meaning: 'Fly — insect', example: 'ఈగ ఆహారం మీద వాలింది.' },
    'ఉ': { word: 'ఉప్పు (Uppu)', meaning: 'Salt', example: 'ఉప్పు వంటకాలలో అవసరం.' },
    'ఊ': { word: 'ఊరు (Ooru)', meaning: 'Village', example: 'నా ఊరు చాలా అందంగా ఉంటుంది.' },
    'ఎ': { word: 'ఎలుక (Eluka)', meaning: 'Rat', example: 'ఎలుక పిల్లి నుండి పారిపోయింది.' },
    'ఏ': { word: 'ఏనుగు (Enugu)', meaning: 'Elephant', example: 'ఏనుగు చాలా పెద్ద జంతువు.' },
    'ఐ': { word: 'ఐదు (Aidu)', meaning: 'Five (number)', example: 'నా దగ్గర ఐదు పుస్తకాలు ఉన్నాయి.' },
    'ఒ': { word: 'ఒంటె (Onte)', meaning: 'Camel', example: 'ఒంటె ఎడారిలో నివసిస్తుంది.' },
    'ఓ': { word: 'ఓడ (Oda)', meaning: 'Ship / Boat', example: 'ఓడ సముద్రంలో ప్రయాణిస్తుంది.' },
    'ఔ': { word: 'ఔషధం (Aushadham)', meaning: 'Medicine', example: 'ఔషధం సరిగ్గా తీసుకోండి.' },
    'క': { word: 'కమలం (Kamalam)', meaning: 'Lotus', example: 'కమలం నీటిలో వికసిస్తుంది.' },
    'ఖ': { word: 'ఖడ్గం (Khadgam)', meaning: 'Sword', example: 'రాజు ఖడ్గం ధరించాడు.' },
    'గ': { word: 'గడియారం (Gadiyaaram)', meaning: 'Clock', example: 'గడియారంలో పది గంటలు అవుతున్నాయి.' },
    'ఘ': { word: 'ఘంట (Ghanta)', meaning: 'Bell', example: 'గుడిలో ఘంట మోగుతుంది.' },
    'చ': { word: 'చంద్రుడు (Chandrudu)', meaning: 'Moon', example: 'చంద్రుడు రాత్రి ప్రకాశిస్తాడు.' },
    'జ': { word: 'జెండా (Jenda)', meaning: 'Flag', example: 'జెండా ఎగురుతోంది.' },
    'ట': { word: 'టమాటా (Tamaata)', meaning: 'Tomato', example: 'టమాటా ఎర్రగా ఉంటుంది.' },
    'డ': { word: 'డప్పు (Dappu)', meaning: 'Drum', example: 'డప్పు మోగుతుంది.' },
    'ణ': { word: 'గుణం (Gunam)', meaning: 'Quality / Virtue', example: 'మంచి గుణాలు నేర్చుకోండి.' },
    'త': { word: 'తార (Taara)', meaning: 'Star', example: 'రాత్రి తారలు మెరుస్తాయి.' },
    'ద': { word: 'దీపం (Deepam)', meaning: 'Lamp', example: 'దీపం వెలుగుతోంది.' },
    'న': { word: 'నది (Nadi)', meaning: 'River', example: 'నది సముద్రంలో కలుస్తుంది.' },
    'ప': { word: 'పువ్వు (Puvvu)', meaning: 'Flower', example: 'పువ్వు తోటలో వికసించింది.' },
    'బ': { word: 'బంతి (Banthi)', meaning: 'Ball / Marigold', example: 'బంతి పువ్వు పసుపు రంగులో ఉంటుంది.' },
    'మ': { word: 'మేఘం (Megham)', meaning: 'Cloud', example: 'ఆకాశంలో మేఘాలు కనిపిస్తున్నాయి.' },
    'య': { word: 'యాత్ర (Yaatra)', meaning: 'Journey', example: 'మేము తిరుపతి యాత్ర చేశాము.' },
    'ర': { word: 'రంగు (Rangu)', meaning: 'Color', example: 'హరివిల్లులో ఏడు రంగులు ఉంటాయి.' },
    'ల': { word: 'లడ్డు (Laddu)', meaning: 'Laddu — sweet ball', example: 'లడ్డు చాలా రుచిగా ఉంటుంది.' },
    'వ': { word: 'వనం (Vanam)', meaning: 'Forest', example: 'వనంలో చాలా జంతువులు ఉన్నాయి.' },
    'శ': { word: 'శంఖం (Shankham)', meaning: 'Conch shell', example: 'శంఖం పూజలో ఉపయోగిస్తారు.' },
    'ష': { word: 'షడ్భుజి (Shadbhuji)', meaning: 'Hexagon', example: 'తేనెగూడు షడ్భుజి ఆకారంలో ఉంటుంది.' },
    'స': { word: 'సూర్యుడు (Suryudu)', meaning: 'Sun', example: 'సూర్యుడు తూర్పున ఉదయిస్తాడు.' },
    'హ': { word: 'హరివిల్లు (Harivillu)', meaning: 'Rainbow', example: 'వర్షం తరువాత హరివిల్లు కనిపిస్తుంది.' }
  },
  // Bengali vocabulary
  bn: {
    'অ': { word: 'অজগর (Ajogor)', meaning: 'Python — large snake', example: 'অজগর বনে থাকে।' },
    'আ': { word: 'আম (Aam)', meaning: 'Mango', example: 'আম গ্রীষ্মকালের ফল।' },
    'ই': { word: 'ইলিশ (Ilish)', meaning: 'Hilsa fish — Bengali delicacy', example: 'ইলিশ মাছ খুব সুস্বাদু।' },
    'ঈ': { word: 'ঈগল (Igol)', meaning: 'Eagle', example: 'ঈগল আকাশে উড়ে।' },
    'উ': { word: 'উট (Ut)', meaning: 'Camel', example: 'উট মরুভূমিতে থাকে।' },
    'ঊ': { word: 'ঊন (Un)', meaning: 'Wool', example: 'ঊন দিয়ে সোয়েটার বোনা হয়।' },
    'এ': { word: 'একতা (Ekota)', meaning: 'Unity', example: 'একতায় শক্তি।' },
    'ঐ': { word: 'ঐতিহ্য (Oitijhyo)', meaning: 'Heritage / Tradition', example: 'বাংলার ঐতিহ্য সমৃদ্ধ।' },
    'ও': { word: 'ওজন (Ojon)', meaning: 'Weight', example: 'ফলের ওজন মাপো।' },
    'ঔ': { word: 'ঔষধ (Oushod)', meaning: 'Medicine', example: 'সময়মতো ঔষধ খাও।' },
    'ক': { word: 'কমল (Komol)', meaning: 'Lotus', example: 'কমল জলে ফোটে।' },
    'খ': { word: 'খরগোশ (Khorgo-sh)', meaning: 'Rabbit', example: 'খরগোশ দ্রুত দৌড়ায়।' },
    'গ': { word: 'গরু (Goru)', meaning: 'Cow', example: 'গরু দুধ দেয়।' },
    'ঘ': { word: 'ঘড়ি (Ghori)', meaning: 'Clock / Watch', example: 'ঘড়িতে দশটা বাজে।' },
    'চ': { word: 'চাঁদ (Chaad)', meaning: 'Moon', example: 'রাতে চাঁদ ওঠে।' },
    'ছ': { word: 'ছাতা (Chata)', meaning: 'Umbrella', example: 'বৃষ্টিতে ছাতা নিয়ে যাও।' },
    'জ': { word: 'জল (Jol)', meaning: 'Water', example: 'জল ছাড়া জীবন নেই।' },
    'ঝ': { word: 'ঝরনা (Jhorna)', meaning: 'Waterfall', example: 'ঝরনার জল ঠান্ডা।' },
    'ট': { word: 'টমেটো (Tometo)', meaning: 'Tomato', example: 'টমেটো লাল রঙের হয়।' },
    'ঠ': { word: 'ঠান্ডা (Thanda)', meaning: 'Cold', example: 'শীতকালে ঠান্ডা পড়ে।' },
    'ড': { word: 'ডাব (Dab)', meaning: 'Tender coconut', example: 'ডাবের জল পান করো।' },
    'ঢ': { word: 'ঢোল (Dhol)', meaning: 'Drum', example: 'পূজায় ঢোল বাজে।' },
    'ণ': { word: 'গুণ (Gun)', meaning: 'Quality / Virtue', example: 'ভালো গুণ শেখো।' },
    'ত': { word: 'তারা (Tara)', meaning: 'Star', example: 'রাতে তারা জ্বলে।' },
    'থ': { word: 'থালা (Thala)', meaning: 'Plate', example: 'থালায় খাবার সাজাও।' },
    'দ': { word: 'দিন (Din)', meaning: 'Day', example: 'আজ সুন্দর দিন।' },
    'ধ': { word: 'ধনুক (Dhonuk)', meaning: 'Bow', example: 'রাম ধনুক তুলেছিলেন।' },
    'ন': { word: 'নদী (Nodi)', meaning: 'River', example: 'গঙ্গা একটি পবিত্র নদী।' },
    'প': { word: 'পাখি (Pakhi)', meaning: 'Bird', example: 'পাখি আকাশে উড়ে।' },
    'ফ': { word: 'ফুল (Phul)', meaning: 'Flower', example: 'বাগানে ফুল ফুটেছে।' },
    'ব': { word: 'বাঘ (Bagh)', meaning: 'Tiger — Royal Bengal Tiger', example: 'বাঘ সুন্দরবনে থাকে।' },
    'ভ': { word: 'ভালুক (Bhaluk)', meaning: 'Bear', example: 'ভালুক মধু খেতে ভালোবাসে।' },
    'ম': { word: 'মাছ (Mach)', meaning: 'Fish', example: 'বাঙালি মাছ ভাত খায়।' },
    'য': { word: 'যাত্রা (Jatra)', meaning: 'Journey / Folk theatre', example: 'আমরা পাহাড়ে যাত্রা করলাম।' },
    'র': { word: 'রং (Rong)', meaning: 'Color', example: 'রামধনুতে সাতটি রং আছে।' },
    'ল': { word: 'লেবু (Lebu)', meaning: 'Lemon', example: 'লেবুর রস টক হয়।' },
    'শ': { word: 'শিশু (Shishu)', meaning: 'Child', example: 'শিশুরা আমাদের ভবিষ্যৎ।' },
    'ষ': { word: 'ষড়যন্ত্র (Shorojontro)', meaning: 'Conspiracy / Plot', example: 'ষড়যন্ত্র থেকে সাবধান।' },
    'স': { word: 'সূর্য (Surjo)', meaning: 'Sun', example: 'সূর্য পূর্বে ওঠে।' },
    'হ': { word: 'হাতি (Hati)', meaning: 'Elephant', example: 'হাতি সবচেয়ে বড় জানোয়ার।' }
  },
  // Marathi vocabulary
  mr: {
    'अ': { word: 'अनार (Anaar)', meaning: 'Pomegranate', example: 'अनार खाल्ल्याने रक्त वाढते.' },
    'आ': { word: 'आंबा (Aamba)', meaning: 'Mango', example: 'आंबा फळांचा राजा आहे.' },
    'इ': { word: 'इमली (Imli)', meaning: 'Tamarind', example: 'इमलीची चव आंबट असते.' },
    'ई': { word: 'ईख (Eekh)', meaning: 'Sugarcane', example: 'ईखापासून साखर बनते.' },
    'उ': { word: 'उंदीर (Undir)', meaning: 'Rat', example: 'उंदीर छोटा प्राणी आहे.' },
    'ऊ': { word: 'ऊन (Oon)', meaning: 'Wool / Sunshine', example: 'ऊनापासून स्वेटर विणतात.' },
    'ए': { word: 'एकता (Ekta)', meaning: 'Unity', example: 'एकतेत बळ आहे.' },
    'ऐ': { word: 'ऐरणी (Airani)', meaning: 'Anvil (blacksmith tool)', example: 'लोहार ऐरणीवर काम करतो.' },
    'ओ': { word: 'ओढणी (Odhani)', meaning: 'Shawl / Scarf', example: 'आजी ओढणी घेऊन बसली.' },
    'औ': { word: 'औषध (Aushadh)', meaning: 'Medicine', example: 'वेळेवर औषध घ्या.' },
    'क': { word: 'कमळ (Kamal)', meaning: 'Lotus', example: 'कमळ पाण्यात फुलतो.' },
    'ख': { word: 'खारीक (Kharik)', meaning: 'Dried date', example: 'खारीक पौष्टिक असते.' },
    'ग': { word: 'गाय (Gaay)', meaning: 'Cow', example: 'गाय दूध देते.' },
    'घ': { word: 'घड्याळ (Ghadyal)', meaning: 'Clock', example: 'घड्याळात दहा वाजले.' },
    'च': { word: 'चंद्र (Chandra)', meaning: 'Moon', example: 'चंद्र रात्री प्रकाशतो.' },
    'छ': { word: 'छत्री (Chhatri)', meaning: 'Umbrella', example: 'पावसात छत्री घ्या.' },
    'ज': { word: 'जहाज (Jahaaj)', meaning: 'Ship', example: 'जहाज समुद्रात तरंगते.' },
    'झ': { word: 'झेंडा (Zhenda)', meaning: 'Flag', example: 'तिरंगा झेंडा फडकतो.' },
    'ट': { word: 'टोमॅटो (Tomato)', meaning: 'Tomato', example: 'टोमॅटो लाल आणि गोल असतो.' },
    'ठ': { word: 'ठंडी (Thandi)', meaning: 'Cold', example: 'हिवाळ्यात खूप ठंडी पडते.' },
    'ड': { word: 'डोळा (Dola)', meaning: 'Eye', example: 'डोळ्यांची काळजी घ्या.' },
    'ढ': { word: 'ढोलकी (Dholki)', meaning: 'Small drum', example: 'ढोलकी लग्नात वाजते.' },
    'ण': { word: 'गुण (Gun)', meaning: 'Quality', example: 'चांगले गुण शिका.' },
    'त': { word: 'तारा (Taara)', meaning: 'Star', example: 'रात्री तारे चमकतात.' },
    'थ': { word: 'थाळी (Thali)', meaning: 'Plate', example: 'थाळीत जेवण वाढा.' },
    'द': { word: 'दूध (Doodh)', meaning: 'Milk', example: 'दूध पिणे आरोग्यासाठी चांगले.' },
    'ध': { word: 'धनुष्य (Dhanushya)', meaning: 'Bow', example: 'रामाने धनुष्य उचलले.' },
    'न': { word: 'नदी (Nadi)', meaning: 'River', example: 'गोदावरी एक पवित्र नदी आहे.' },
    'प': { word: 'पक्षी (Pakshi)', meaning: 'Bird', example: 'पक्षी आकाशात उडतो.' },
    'फ': { word: 'फुल (Phul)', meaning: 'Flower', example: 'बागेत सुंदर फुले फुलली.' },
    'ब': { word: 'बाग (Baag)', meaning: 'Garden', example: 'बागेत सुंदर फुले आहेत.' },
    'भ': { word: 'भाकरी (Bhakri)', meaning: 'Flatbread (Maharashtrian)', example: 'भाकरी आणि ठेचा छान लागतो.' },
    'म': { word: 'मोर (Mor)', meaning: 'Peacock', example: 'मोर पावसात नाचतो.' },
    'य': { word: 'यात्रा (Yatra)', meaning: 'Journey', example: 'आम्ही पंढरपूरची यात्रा केली.' },
    'र': { word: 'रंग (Rang)', meaning: 'Color', example: 'इंद्रधनुष्यात सात रंग असतात.' },
    'ल': { word: 'लाडू (Ladoo)', meaning: 'Sweet ball', example: 'लाडू सणासुदीला बनवतात.' },
    'व': { word: 'वन (Van)', meaning: 'Forest', example: 'वनात अनेक प्राणी राहतात.' },
    'श': { word: 'शेर (Sher)', meaning: 'Lion', example: 'शेर जंगलचा राजा आहे.' },
    'ष': { word: 'षट्कोन (Shatkon)', meaning: 'Hexagon', example: 'मधाच्या पोळ्याचा आकार षट्कोन असतो.' },
    'स': { word: 'सूर्य (Surya)', meaning: 'Sun', example: 'सूर्य पूर्वेला उगवतो.' },
    'ह': { word: 'हत्ती (Hatti)', meaning: 'Elephant', example: 'हत्ती सर्वात मोठा प्राणी आहे.' },
    'ळ': { word: 'वेळ (Vel)', meaning: 'Time (unique Marathi)', example: 'वेळ खूप महत्त्वाची आहे.' }
  },
  // Marwadi vocabulary (uses Devanagari like Hindi, but local words)
  mwr: {
    'अ': { word: 'अनार (Anaar)', meaning: 'Pomegranate', example: 'अनार खाय सूं लोही बढ़ै।' },
    'आ': { word: 'आम (Aam)', meaning: 'Mango', example: 'आम गरमी रो फळ है।' },
    'इ': { word: 'इमली (Imli)', meaning: 'Tamarind', example: 'इमली रो स्वाद खट्टो लागै।' },
    'ई': { word: 'ईख (Eekh)', meaning: 'Sugarcane', example: 'ईख सूं गुड़ बणै।' },
    'उ': { word: 'उल्लू (Ullu)', meaning: 'Owl', example: 'उल्लू रात नै जागै।' },
    'ऊ': { word: 'ऊन (Oon)', meaning: 'Wool', example: 'ऊन सूं स्वेटर बणावै।' },
    'ए': { word: 'एकता (Ekta)', meaning: 'Unity', example: 'एकता में बोत बल है।' },
    'ऐ': { word: 'ऐनक (Ainak)', meaning: 'Spectacles', example: 'दादोसा ऐनक लगा नै पढ़ै।' },
    'ओ': { word: 'ओखली (Okhli)', meaning: 'Mortar', example: 'ओखली में मसालो कूटै।' },
    'औ': { word: 'औरत (Aurat)', meaning: 'Woman', example: 'हर औरत रो सम्मान करो।' },
    'क': { word: 'कमल (Kamal)', meaning: 'Lotus', example: 'कमल पाणी में खिलै।' },
    'ख': { word: 'खरगोश (Khargosh)', meaning: 'Rabbit', example: 'खरगोश बोत तेज भागै।' },
    'ग': { word: 'गमलो (Gamlo)', meaning: 'Flower pot', example: 'गमलै में सुंदर फूल लाग्या।' },
    'घ': { word: 'घड़ी (Ghadi)', meaning: 'Clock', example: 'घड़ी में दस बज रया है।' },
    'च': { word: 'चम्मच (Chammach)', meaning: 'Spoon', example: 'चम्मच सूं खाणो खाओ।' },
    'छ': { word: 'छाता (Chhata)', meaning: 'Umbrella', example: 'बरसात में छाता ले जाओ।' },
    'ज': { word: 'जहाज (Jahaaj)', meaning: 'Ship / Airplane', example: 'जहाज आसमान में उड़ रयो है।' },
    'झ': { word: 'झंडो (Jhando)', meaning: 'Flag', example: 'तिरंगो झंडो म्हारो गौरव है।' },
    'ट': { word: 'टमाटर (Tamatar)', meaning: 'Tomato', example: 'टमाटर लाल अर गोल होवै।' },
    'ठ': { word: 'ठंडी (Thandi)', meaning: 'Cold', example: 'ज्यादा में बोत ठंडी पड़ै।' },
    'ड': { word: 'डमरू (Damru)', meaning: 'Small drum', example: 'शिवजी डमरू बजावै।' },
    'ढ': { word: 'ढोल (Dhol)', meaning: 'Drum', example: 'ब्याव में ढोल बजै।' },
    'ण': { word: 'गुण (Gun)', meaning: 'Quality', example: 'आछा गुण अपणाओ।' },
    'त': { word: 'तारो (Taaro)', meaning: 'Star', example: 'रात नै तारा चमकै।' },
    'थ': { word: 'थाली (Thali)', meaning: 'Plate', example: 'थाली में खाणो परोसो।' },
    'द': { word: 'दवाई (Dawai)', meaning: 'Medicine', example: 'बीमार होवै तो दवाई खाओ।' },
    'ध': { word: 'धनुष (Dhanush)', meaning: 'Bow', example: 'राम धनुष उठायो।' },
    'न': { word: 'नदी (Nadi)', meaning: 'River', example: 'लूणी एक राजस्थान री नदी है।' },
    'प': { word: 'पतंग (Patang)', meaning: 'Kite', example: 'छोरा पतंग उड़ावै।' },
    'फ': { word: 'फूल (Phool)', meaning: 'Flower', example: 'बाग में सुंदर फूल खिल्या।' },
    'ब': { word: 'बादल (Baadal)', meaning: 'Cloud', example: 'आसमान में बादल छा रया।' },
    'भ': { word: 'भालू (Bhalu)', meaning: 'Bear', example: 'भालू जंगल में रहवै।' },
    'म': { word: 'मोर (Mor)', meaning: 'Peacock', example: 'मोर बरसात में नाचै।' },
    'य': { word: 'यात्रा (Yatra)', meaning: 'Journey', example: 'म्हे पुष्कर री यात्रा करी।' },
    'र': { word: 'रंग (Rang)', meaning: 'Color', example: 'होली पै रंग खेलै।' },
    'ल': { word: 'लाडू (Ladoo)', meaning: 'Sweet ball', example: 'लाडू तीज पै बणावै।' },
    'व': { word: 'वन (Van)', meaning: 'Forest', example: 'वन में बोत सा जानवर रहवै।' },
    'श': { word: 'शेर (Sher)', meaning: 'Lion', example: 'शेर जंगल रो राजा है।' },
    'स': { word: 'सूरज (Suraj)', meaning: 'Sun', example: 'सूरज पूरब सूं उगै।' },
    'ह': { word: 'हाथी (Haathi)', meaning: 'Elephant', example: 'हाथी सबसूं बड़ो जानवर है।' }
  }
};
